version: '2'

services:
  web:
    build: flask/.
    command: python -u app.py
    ports:
      - "5000:5000"
    volumes:
      - ./flask:/todo
    links:
      - db
    environment:
      MONGODB_HOST: db
    networks:
      - db_net

  db:
    image: mongo:3.0.2
    container_name: mongo
    networks:
      - db_net

networks:
  db_net:
